// CancunPeptide catalog — prices in MXN and USD (~18.5 MXN/USD)
// Pricing strategy: Zelara parity on winners, US-competitive on the rest.
const PRODUCTS = [
  { id: "bpc-157",       name: "BPC-157",                        spec: "5 mg",   price: 673,  usd: 36,  cat: "regeneracion", img: "img/vials/bpc-157.png",
    desc: "Pentadecapeptide studied for its role in tissue repair and gastrointestinal tract models." },
  { id: "retatrutida",   name: "Retatrutide",                    spec: "10 mg",  price: 2070, usd: 112, cat: "metabolico",   img: "img/vials/retatrutida.png",
    desc: "Triple GIP/GLP-1/glucagon agonist under investigation for energy metabolism and body composition." },
  { id: "tirzepatida",   name: "Tirzepatide",                    spec: "15 mg",  price: 1549, usd: 84,  cat: "metabolico",   img: "img/vials/tirzepatida.png",
    desc: "Dual GIP/GLP-1 agonist in research on metabolism, weight and insulin sensitivity." },
  { id: "tb-500",        name: "TB-500 (Thymosin Beta 4)",       spec: "5 mg",   price: 1090, usd: 59,  cat: "regeneracion", img: "img/vials/tb-500.png",
    desc: "Thymosin beta-4 fragment studied in cell migration and muscle recovery models." },
  { id: "semaglutida-5", name: "Semaglutide",                    spec: "5 mg",   price: 830,  usd: 45,  cat: "metabolico",   img: "img/vials/semaglutida-5.png",
    desc: "The most studied GLP-1 agonist worldwide, in metabolic and glycemic control research." },
  { id: "semaglutida-10",name: "Semaglutide",                    spec: "10 mg",  price: 1090, usd: 59,  cat: "metabolico",   img: "img/vials/semaglutida-10.png",
    desc: "The most studied GLP-1 agonist worldwide, in metabolic and glycemic control research. 10 mg presentation." },
  { id: "ghk-cu",        name: "GHK-Cu (Copper)",                spec: "50 mg",  price: 518,  usd: 28,  cat: "regeneracion", img: "img/vials/ghk-cu.png",
    desc: "Copper tripeptide studied in skin regeneration, hair follicle and connective tissue models." },
  { id: "ghk-cu-100",    name: "GHK-Cu (Copper)",                spec: "100 mg", price: 830,  usd: 45,  cat: "regeneracion", img: "img/vials/ghk-cu-100.png",
    desc: "Copper tripeptide studied in skin regeneration, hair follicle and connective tissue models. 100 mg presentation." },
  { id: "ipamorelin",    name: "Ipamorelin",                     spec: "5 mg",   price: 590,  usd: 32,  cat: "secretagogo",  img: "img/vials/ipamorelin.png",
    desc: "Highly selective GH secretagogue, a reference in GH/IGF-1 axis research." },
  { id: "ipamorelin-10", name: "Ipamorelin",                     spec: "10 mg",  price: 1090, usd: 59,  cat: "secretagogo",  img: "img/vials/ipamorelin-10.png",
    desc: "Highly selective GH secretagogue, a reference in GH/IGF-1 axis research. 10 mg presentation." },
  { id: "epithalon",     name: "Epithalon",                      spec: "10 mg",  price: 621,  usd: 34,  cat: "longevidad",   img: "img/vials/epithalon.png",
    desc: "Pineal tetrapeptide studied for its relation to telomerase and cellular aging models." },
  { id: "nad",           name: "NAD+",                           spec: "500 mg", price: 1200, usd: 65,  cat: "longevidad",   img: "img/vials/nad.png",
    desc: "Central coenzyme in cellular metabolism, sirtuin pathways and aging research." },
  { id: "selank",        name: "Selank",                         spec: "5 mg",   price: 673,  usd: 36,  cat: "cognitivo",    img: "img/vials/selank.png",
    desc: "Tuftsin-analog heptapeptide studied in anxiety and cognitive process models." },
  { id: "semax",         name: "Semax",                          spec: "5 mg",   price: 658,  usd: 36,  cat: "cognitivo",    img: "img/vials/semax.png",
    desc: "ACTH(4-10) analog heptapeptide studied in attention, memory and neuroprotection models." },
  { id: "oxitocina-5",   name: "Oxytocin",                       spec: "5 mg",   price: 549,  usd: 30,  cat: "cognitivo",    img: "img/vials/oxitocina-5.png",
    desc: "Natural neuropeptide under investigation on social bonding, mood and stress response." },
  { id: "oxitocina-10",  name: "Oxytocin",                       spec: "10 mg",  price: 1199, usd: 65,  cat: "cognitivo",    img: "img/vials/oxitocina-10.png",
    desc: "Natural neuropeptide under investigation on social bonding, mood and stress response. 10 mg presentation." },
  { id: "mots-c",        name: "MOTS-c",                         spec: "10 mg",  price: 1242, usd: 67,  cat: "metabolico",   img: "img/vials/mots-c.png",
    desc: "Mitochondrial-DNA-encoded peptide in research on metabolism, exercise and insulin sensitivity." },
  { id: "5amino1mq",     name: "5-Amino-1MQ",                    spec: "10 mg",  price: 1188, usd: 64,  cat: "metabolico",   img: "img/vials/5amino1mq.png",
    desc: "NNMT inhibitor in research on cellular energy metabolism and NAD+." },
  { id: "kpv",           name: "KPV",                            spec: "5 mg",   price: 1724, usd: 93,  cat: "regeneracion", img: "img/vials/kpv.png",
    desc: "α-MSH-derived tripeptide studied in intestinal and dermal inflammation models." },
  { id: "melanotan-1",   name: "Melanotan 1",                    spec: "10 mg",  price: 830,  usd: 45,  cat: "pigmentacion", img: "img/vials/melanotan-1.png",
    desc: "Linear α-MSH analog in research on melanogenesis and pigmentary response." },
  { id: "melanotan-2",   name: "Melanotan 2",                    spec: "10 mg",  price: 830,  usd: 45,  cat: "pigmentacion", img: "img/vials/melanotan-2.png",
    desc: "Cyclic α-MSH analog studied in pigmentation and melanocortin models." },
  { id: "tesamorelin",   name: "Tesamorelin",                    spec: "10 mg",  price: 2590, usd: 140, cat: "metabolico",   img: "img/vials/tesamorelin.png",
    desc: "GHRH analog investigated in body composition and visceral fat research." },
  { id: "ipa-cjc",       name: "Ipamorelin + CJC-1295 No-DAC",   spec: "10 mg",  price: 2940, usd: 159, cat: "secretagogo",  img: "img/vials/ipa-cjc.png",
    desc: "Synergistic blend of two secretagogues for GH/IGF-1 axis research with physiological pulses." },
  { id: "bpc-tb",        name: "BPC-157 + TB-500",               spec: "10 mg",  price: 3024, usd: 163, cat: "regeneracion", img: "img/vials/bpc-tb.png",
    desc: "Combined blend for broad tissue recovery and repair models." },
  { id: "bpc-tb-20",     name: "BPC-157 + TB-500",               spec: "20 mg",  price: 3699, usd: 200, cat: "regeneracion", img: "img/vials/bpc-tb-20.png",
    desc: "Combined blend for broad tissue recovery and repair models. 20 mg presentation." },
  { id: "glow",          name: "GLOW",                           spec: "70 mg",  price: 3456, usd: 187, cat: "blend",        img: "img/vials/glow.png",
    desc: "GHK-Cu, BPC-157 and TB-500 blend aimed at skin and general regeneration research." },
  { id: "klow",          name: "KLOW",                           spec: "80 mg",  price: 5039, usd: 272, cat: "blend",        img: "img/vials/klow.png",
    desc: "GHK-Cu, BPC-157, TB-500 and KPV blend for combined inflammation and regeneration models." },
  { id: "agua-bac",      name: "Bacteriostatic Water",           spec: "3 mL",   price: 37,   usd: 2,   cat: "accesorio",    img: "img/vials/agua-bac.png",
    note: "Diluent for reconstituting lyophilized peptides",
    desc: "Sterile water with 0.9% benzyl alcohol, the lab standard for reconstituting lyophilized peptides. At cost (≈ $2 USD)." }
];

const CATEGORIES = {
  todos:        "All",
  metabolico:   "Metabolic",
  regeneracion: "Recovery",
  cognitivo:    "Cognitive",
  longevidad:   "Longevity",
  secretagogo:  "Secretagogues",
  pigmentacion: "Tanning",
  blend:        "Blends",
  accesorio:    "Supplies"
};

// Common specs shown in every product sheet
const SPECS_COMUNES = [
  "Purity ≥99% verified by HPLC",
  "Molecular identity confirmed by mass spectrometry (MS)",
  "Lot-traceable Certificate of Analysis (COA)",
  "Form: lyophilized powder in vacuum-sealed vial",
  "Recommended storage: -20 °C, protected from light and humidity",
  "For research use only"
];
